Config = Config or {}

Config.ShortCalls = false -- Dispatch notifications are sent containing only the alert name, omitting additional details. For more information, the dispatch menu can be accessed.  
Config.Debug = false -- Enables debug and send alerts when leo break the law.

Config.RespondKeybind = 'E'
Config.OpenDispatchMenu = 'O'
Config.AlertTime = 15     -- Specify the duration for the alert to appear on the screen. The default time is 5 seconds for all alerts. To set a different duration for specific alerts, change the value in `alertTime = nil` found in the alerts.lua file.

Config.MaxCallList = 25 -- maximum dispatch calls in dispatch list
Config.OnDutyOnly = true -- Set true if only on duty players can see the alert
Config.Jobs = { -- Job Types that can access the dispatch menu
    "police",
    "ambulance",
    "bcso",
    "sikkerhet"
}

Config.DefaultAlertsDelay = 5 -- Delay between each default alert, prevent spamming
Config.DefaultAlerts = {
    Speeding = false,
    Shooting = true,
    Autotheft = false,
    Melee = false,
    PlayerDowned = true,
    Explosion = false
}

Config.MinOffset = 1
Config.MaxOffset = 120

Config.PhoneRequired = true -- Set true if only can use 911/311 command when got a phone on inventory.
Config.PhoneItems = { -- Add the entire list of your phone items.
    "phone",
}

-- Locations for the Hunting Zones and No Dispatch Zones( Label: Name of Blip // Radius: Radius of the Alert and Blip)
Config.EnableHuntingBlip = false

Config.Locations = {
    ["HuntingZones"] = {
        [1] = {label = "Hunting Zone", radius = 650.0, coords = vector3(-938.61, 4823.99, 313.92)},
    },
    ["NoDispatchZones"] = {
        [1] = {label = "Ammunation 1", coords = vector3(13.53, -1097.92, 29.8), length = 14.0, width = 5.0, heading = 70, minZ = 28.8, maxZ = 32.8},
        [2] = {label = "Ammunation 2", coords = vector3(821.96, -2163.09, 29.62), length = 14.0, width = 5.0, heading = 270, minZ = 28.62, maxZ = 32.62},
    },
}

-- Whitelist Guns that do not send shooting alerts
Config.WeaponWhitelist = {
    'WEAPON_GRENADE',
    'WEAPON_BZGAS',
    'WEAPON_MOLOTOV',
    'WEAPON_STICKYBOMB',
    'WEAPON_PROXMINE',
    'WEAPON_SNOWBALL',
    'WEAPON_PIPEBOMB',
    'WEAPON_BALL',
    'WEAPON_SMOKEGRENADE',
    'WEAPON_FLARE',
    'WEAPON_PETROLCAN',
    'WEAPON_FIREEXTINGUISHER',
    'WEAPON_HAZARDCAN',
    'WEAPON_RAYCARBINE',
    'WEAPON_STUNGUN',
    'WEAPON_PLASMAP',
	'WEAPON_RAZORBACK',
	'WEAPON_NEEDLER2',
	'WEAPON_RAYSHOTGUN',
    'weapon_bullpuprifle',
    'weapon_appistol',
    'weapon_snspistol',
    'weapon_molotov',
    'weapon_grenade',
    'weapon_heavysniperrifle',
    'weapon_sniperrifle',
    'WEAPON_PAINTBALL',
}

Config.Blips = {
    ['vehicleshots'] = { -- Need to match the codeName in alerts.lua
        radius = 0,
        sprite = 119,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['shooting'] = {
        radius = 0,
        sprite = 110,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['speeding'] = {
        radius = 0,
        sprite = 326,
        color = 84,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['fight'] = {
        radius = 0,
        sprite = 685,
        color = 69,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['civdown'] = {
        radius = 0,
        sprite = 126,
        color = 3,
        scale = 1.5,
        length = 2,
        sound = 'dispatch',
        offset = false,
        flash = false
    },
    ['civdead'] = {
        radius = 0,
        sprite = 126,
        color = 3,
        scale = 1.5,
        length = 2,
        sound = 'dispatch',
        offset = false,
        flash = false
    },
    ['911call'] = {
        radius = 0,
        sprite = 480,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['311call'] = {
        radius = 0,
        sprite = 480,
        color = 3,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['officerdown'] = {
        radius = 15.0,
        sprite = 526,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = true
    },
    ['officerbackup'] = {
        radius = 15.0,
        sprite = 526,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = true
    },
    ['officerdistress'] = {
        radius = 15.0,
        sprite = 526,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = true
    },
    ['emsdown'] = {
        radius = 15.0,
        sprite = 526,
        color = 3,
        scale = 1.5,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = false
    },
    ['hunting'] = {
        radius = 0,
        sprite = 141,
        color = 2,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['storerobbery'] = {
        radius = 0,
        sprite = 52,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['bankrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 2,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },

    ['ubatran'] = {
        radius = 0,
        sprite = 500,
        color = 2,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['paletobankrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 12,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['pacificbankrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 5,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['prisonbreak'] = {
        radius = 0,
        sprite = 189,
        color = 59,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['vangelicorobbery'] = {
        radius = 0,
        sprite = 434,
        color = 5,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['houserobbery'] = {
        radius = 0,
        sprite = 40,
        color = 5,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['suspicioushandoff'] = {
        radius = 120.0,
        sprite = 469,
        color = 52,
        scale = 0,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = true,
        flash = false
    },

    ['transport'] = {
        radius = 120.0,
        sprite = 469,
        color = 52,
        scale = 0,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = true,
        flash = false
    },
    ['yachtheist'] = {
        radius = 0,
        sprite = 455,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['vehicletheft'] = {
        radius = 0,
        sprite = 595,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['signrobbery'] = {
        radius = 0,
        sprite = 358,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['susactivity'] = {
        radius = 0,
        sprite = 66,
        color = 37,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    -- Rainmad Scripts
    ['artgalleryrobbery'] = {
        radius = 0,
        sprite = 269,
        color = 59,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['humanelabsrobbery'] = {
        radius = 0,
        sprite = 499,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['trainrobbery'] = {
        radius = 0,
        sprite = 667,
        color = 78,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['vanrobbery'] = {
        radius = 0,
        sprite = 67,
        color = 59,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['undergroundrobbery'] = {
        radius = 0,
        sprite = 486,
        color = 59,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['drugboatrobbery'] = {
        radius = 0,
        sprite = 427,
        color = 26,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['unionrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['carboosting'] = {
        radius = 0,
        sprite = 595,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['carjack'] = {
        radius = 0,
        sprite = 595,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['explosion'] = {
        radius = 75.0,
        sprite = 436,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = true,
        flash = false
    }
}

Config.Colors = {
    ['0'] = "Metallisk Svart",
    ['1'] = "Metallisk Grafittsvart",
    ['2'] = "Metallisk Sort Stål",
    ['3'] = "Metallisk Mørk Sølv",
    ['4'] = "Metallisk Sølv",
    ['5'] = "Metallisk Blå Sølv",
    ['6'] = "Metallisk Stålgrå",
    ['7'] = "Metallisk Skyggesølv",
    ['8'] = "Metallisk Steinsølv",
    ['9'] = "Metallisk Midnattsølv",
    ['10'] = "Metallisk Gun metal",
    ['11'] = "Metallisk Antrasittgrå",
    ['12'] = "Matt Svart",
    ['13'] = "Matt Grå",
    ['14'] = "Matt Lys Grå",
    ['15'] = "Bruk Svart",
    ['16'] = "Bruk Svart Poly",
    ['17'] = "Bruk Mørk Sølv",
    ['18'] = "Bruk Sølv",
    ['19'] = "Bruk Skytevåpen",
    ['20'] = "Bruk Skyggesølv",
    ['21'] = "Slitt Svart",
    ['22'] = "Slitt Grafitt",
    ['23'] = "Slitt Sølvgrå",
    ['24'] = "Slitt Sølv",
    ['25'] = "Slitt Blå Sølv",
    ['26'] = "Slitt Skyggesølv",
    ['27'] = "Metallisk Rød",
    ['28'] = "Metallisk Torino Rød",
    ['29'] = "Metallisk Formel Rød",
    ['30'] = "Metallisk Blaze Rød",
    ['31'] = "Metallisk Graceful Rød",
    ['32'] = "Metallisk Granatrød",
    ['33'] = "Metallisk Ørken Rød",
    ['34'] = "Metallisk Cabernet Rød",
    ['35'] = "Metallisk Candy Rød",
    ['36'] = "Metallisk Soloppgang Oransje",
    ['37'] = "Metallisk Klassisk Gull",
    ['38'] = "Metallisk Oransje",
    ['39'] = "Matt Rød",
    ['40'] = "Matt Mørk Rød",
    ['41'] = "Matt Oransje",
    ['42'] = "Matt Gul",
    ['43'] = "Bruk Rød",
    ['44'] = "Bruk Lys Rød",
    ['45'] = "Bruk Granatrød",
    ['46'] = "Slitt Rød",
    ['47'] = "Slitt Gullrød",
    ['48'] = "Slitt Mørk Rød",
    ['49'] = "Metallisk Mørk Grønn",
    ['50'] = "Metallisk Racing Grønn",
    ['51'] = "Metallisk Sjøgrønn",
    ['52'] = "Metallisk Oliven Grønn",
    ['53'] = "Metallisk Grønn",
    ['54'] = "Metallisk Bensin Blå Grønn",
    ['55'] = "Matt Lime Grønn",
    ['56'] = "Bruk Mørk Grønn",
    ['57'] = "Bruk Grønn",
    ['58'] = "Slitt Mørk Grønn",
    ['59'] = "Slitt Grønn",
    ['60'] = "Slitt Sjøvask",
    ['61'] = "Metallisk Midnatt Blå",
    ['62'] = "Metallisk Mørk Blå",
    ['63'] = "Metallisk Sachsen Blå",
    ['64'] = "Metallisk Blå",
    ['65'] = "Metallisk Mariner Blå",
    ['66'] = "Metallisk Havne Blå",
    ['67'] = "Metallisk Diamant Blå",
    ['68'] = "Metallisk Surf Blå",
    ['69'] = "Metallisk Nautisk Blå",
    ['70'] = "Metallisk Lys Blå",
    ['71'] = "Metallisk Lilla Blå",
    ['72'] = "Metallisk Spinnaker Blå",
    ['73'] = "Metallisk Ultra Blå",
    ['74'] = "Metallisk Lys Blå",
    ['75'] = "Bruk Mørk Blå",
    ['76'] = "Bruk Midnatt Blå",
    ['77'] = "Bruk Blå",
    ['78'] = "Bruk Havskum Blå",
    ['79'] = "Bruk Lysning Blå",
    ['80'] = "Bruk Maui Blå Poly",
    ['81'] = "Bruk Lys Blå",
    ['82'] = "Matt Mørk Blå",
    ['83'] = "Matt Blå",
    ['84'] = "Matt Midnatt Blå",
    ['85'] = "Slitt Mørk Blå",
    ['86'] = "Slitt Blå",
    ['87'] = "Slitt Lys Blå",
    ['88'] = "Metallisk Taxi Gul",
    ['89'] = "Metallisk Racing Gul",
    ['90'] = "Metallisk Bronse",
    ['91'] = "Metallisk Gul Fugl",
    ['92'] = "Metallisk Lime",
    ['93'] = "Metallisk Champagne",
    ['94'] = "Metallisk Pueblo Beige",
    ['95'] = "Metallisk Mørk Elfenben",
    ['96'] = "Metallisk Sjokoladebrun",
    ['97'] = "Metallisk Gyldenbrun",
    ['98'] = "Metallisk Lys Brun",
    ['99'] = "Metallisk Strå Beige",
    ['100'] = "Metallisk Mosebrun",
    ['101'] = "Metallisk Biston Brun",
    ['102'] = "Metallisk Bøke Tre",
    ['103'] = "Metallisk Mørk Bøke Tre",
    ['104'] = "Metallisk Sjokolade Appelsin",
    ['105'] = "Metallisk Strand Sand",
    ['106'] = "Metallisk Solbleket Sand",
    ['107'] = "Metallisk Krem",
    ['108'] = "Bruk Brun",
    ['109'] = "Bruk Medium Brun",
    ['110'] = "Bruk Lys Brun",
    ['111'] = "Metallisk Hvit",
    ['112'] = "Metallisk Frost Hvit",
    ['113'] = "Slitt Honning Beige",
    ['114'] = "Slitt Brun",
    ['115'] = "Slitt Mørk Brun",
    ['116'] = "Slitt Strå Beige",
    ['117'] = "Børstet Stål",
    ['118'] = "Børstet Svart Stål",
    ['119'] = "Børstet Aluminium",
    ['120'] = "Krom",
    ['121'] = "Slitt Av Hvit",
    ['122'] = "Bruk Av Hvit",
    ['123'] = "Slitt Oransje",
    ['124'] = "Slitt Lys Oransje",
    ['125'] = "Metallisk Securicor Grønn",
    ['126'] = "Slitt Taxi Gul",
    ['127'] = "Politi Bil Blå",
    ['128'] = "Matt Grønn",
    ['129'] = "Matt Brun",
    ['130'] = "Slitt Oransje",
    ['131'] = "Matt Hvit",
    ['132'] = "Slitt Hvit",
    ['133'] = "Slitt Oliven Arme Grønn",
    ['134'] = "Ren Hvit",
    ['135'] = "Hot Pink",
    ['136'] = "Laksefarget Rosa",
    ['137'] = "Metallisk Vermillion Rosa",
    ['138'] = "Oransje",
    ['139'] = "Grønn",
    ['140'] = "Blå",
    ['141'] = "Metallisk Svart Blå",
    ['142'] = "Metallisk Svart Lilla",
    ['143'] = "Metallisk Svart Rød",
    ['144'] = "Jeger Grønn",
    ['145'] = "Metallisk Lilla",
    ['146'] = "Metallisk Mørk Blå",
    ['147'] = "Svart",
    ['148'] = "Matt Lilla",
    ['149'] = "Matt Mørk Lilla",
    ['150'] = "Metallisk Lava Rød",
    ['151'] = "Matt Skog Grønn",
    ['152'] = "Matt Oliven Grønn",
    ['153'] = "Matt Ørken Brun",
    ['154'] = "Matt Ørken Tan",
    ['155'] = "Matt Foliage Grønn",
    ['156'] = "Standard Legeringsfarge",
    ['157'] = "Epsilon Blå",
    ['158'] = "Ren Gull",
    ['159'] = "Børstet Gull",
    ['160'] = "MP100"
}
